[config.custom_colors]
green = { color = "#81c784", blend = false }
yellow = { color = "#f9e2af", blend = false }

[templates.ghostty]
input_path = "templates/ghostty"
output_path = "~/.config/ghostty/themes/Matugen"
post_hook = "pkill -SIGUSR2 ghostty"

[templates.hyprland]
input_path = 'templates/colors.lua'
output_path = '~/.config/hypr/config/colors.lua'
post_hook = 'hyprctl reload'

[templates.rofi]
input_path = 'templates/colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.kitty]
input_path = "templates/kitty.conf"
output_path = "~/.config/kitty/theme.conf"

[templates.quickshell]
input_path = "templates/quickshell.json"
output_path = "~/.local/state/quickshell/generated/colors.json"
