palette = 0=#1e1f25
palette = 1=#ffb4ab
palette = 2=#495d92
palette = 3=#e1bbdc
palette = 4=#b3c5ff
palette = 5=#ff705e
palette = 6=#314578
palette = 7=#c1c6dd
palette = 8=#38393f
palette = 9=#ffcbc4
palette = 10=#0c1f4a
palette = 11=#e9cde5
palette = 12=#ccd8ff
palette = 13=#ff8678
palette = 14=#384f8a
palette = 15=#d1d5e6

background = #121318
foreground = #e3e2e9
cursor-color = #b3c5ff
# cursor-text-color = #192e60
selection-background = #121318
selection-foreground = #e3e2e9
