// Generated by Matugen
pragma Singleton

import Quickshell
import QtQuick

Singleton {

    property QtObject palette

    palette: QtObject {

        property color background: "#121318"

        property color error: "#ffb4ab"

        property color error_container: "#93000a"

        property color green: "#9ed49d"

        property color green_container: "#1f5027"

        property color green_source: "#81c784"

        property color green_value: "#81c784"

        property color inverse_on_surface: "#2f3036"

        property color inverse_primary: "#495d92"

        property color inverse_surface: "#e3e2e9"

        property color on_background: "#e3e2e9"

        property color on_error: "#690005"

        property color on_error_container: "#ffdad6"

        property color on_green: "#043912"

        property color on_green_container: "#b9f0b7"

        property color on_primary: "#192e60"

        property color on_primary_container: "#dae1ff"

        property color on_primary_fixed: "#001849"

        property color on_primary_fixed_variant: "#314578"

        property color on_secondary: "#2a3042"

        property color on_secondary_container: "#dde2f9"

        property color on_secondary_fixed: "#151b2c"

        property color on_secondary_fixed_variant: "#414659"

        property color on_surface: "#e3e2e9"

        property color on_surface_variant: "#c5c6d0"

        property color on_tertiary: "#422741"

        property color on_tertiary_container: "#ffd6f9"

        property color on_tertiary_fixed: "#2b122b"

        property color on_tertiary_fixed_variant: "#5a3d58"

        property color on_yellow: "#3e2e00"

        property color on_yellow_container: "#ffdf93"

        property color outline: "#8f909a"

        property color outline_variant: "#45464f"

        property color primary: "#b3c5ff"

        property color primary_container: "#314578"

        property color primary_fixed: "#dae1ff"

        property color primary_fixed_dim: "#b3c5ff"

        property color scrim: "#000000"

        property color secondary: "#c1c6dd"

        property color secondary_container: "#414659"

        property color secondary_fixed: "#dde2f9"

        property color secondary_fixed_dim: "#c1c6dd"

        property color shadow: "#000000"

        property color source_color: "#0c1f4a"

        property color surface: "#121318"

        property color surface_bright: "#38393f"

        property color surface_container: "#1e1f25"

        property color surface_container_high: "#292a2f"

        property color surface_container_highest: "#33343a"

        property color surface_container_low: "#1a1b21"

        property color surface_container_lowest: "#0d0e13"

        property color surface_dim: "#121318"

        property color surface_tint: "#b3c5ff"

        property color surface_variant: "#45464f"

        property color tertiary: "#e1bbdc"

        property color tertiary_container: "#5a3d58"

        property color tertiary_fixed: "#ffd6f9"

        property color tertiary_fixed_dim: "#e1bbdc"

        property color yellow: "#e5c36c"

        property color yellow_container: "#594400"

        property color yellow_source: "#f9e2af"

        property color yellow_value: "#f9e2af"
    }
}
