---------------------------------
-- hl group overrides

-- Some overrides are located in
-- plugins/chadrc.lua
---------------------------------
-- vim.api.nvim_set_hl(0, "SnacksDashboardIcon", { fg = "#b4befe" })
-- vim.api.nvim_set_hl(0, "SnacksDashboardDesc", { fg = "#b4befe" })
-- vim.api.nvim_set_hl(0, "SnacksDashboardKey", { fg = "#45475a" })
-- vim.api.nvim_set_hl(0, "SnacksDashboardSpecial", { fg = "#f2cdcd" })
-- vim.api.nvim_set_hl(0, "@lsp.type.property.lua", { fg = "#f38ba8" })
-- vim.api.nvim_set_hl(0, "@property.lua", { fg = "#f38ba8" })
-- vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = "#94e2d5" })
-- vim.api.nvim_set_hl(0, "DiagnosticSignHint", { fg = "#94e2d5" })
-- vim.api.nvim_set_hl(0, "DiagnosticVirtualTextHint", { fg = "#94e2d5" })
