console_title_template = '{{ .Shell }}'
version = 3
final_space = true

# [palette]
#   git_status = '#c6a0f6'
#   git = '#6e738d'
#   error = '#ed8796'
#   primary = '#f4dbd6'
#   date = '#a5adcb'
#   path = '#cad3f5'
#   time = '#eed49f'

[transient_prompt]
  template = '󰘧 '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}green{{end}}']

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    template = '{{ div .Ms 1000 }}s'
    foreground = 'yellow'
    background = 'transparent'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ .CurrentDate | date .Format }} '
    foreground = '8'
    type = 'time'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    foreground = 'cyan'
    type = 'path'
    style = 'plain'
    template = '{{ .Path }}'

    [blocks.segments.properties]
      cache_duration = 'none'
      folder_icon = '󰉋'
      max_width = 0
      style = 'full'

  [[blocks.segments]]
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <magenta>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'
    foreground = '8'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ''
      cache_duration = 'none'
      fetch_status = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '󰘧'
    # ❯  󰘧 󰞷
    # ❯ ❭ 〉 › ❯ 
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}blue{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'
