// Generated by Matugen
pragma Singleton

import Quickshell
import QtQuick

Singleton {

    readonly property color background: "#121318"

    readonly property color error: "#ffb4ab"

    readonly property color error_container: "#93000a"

    readonly property color green: "#9ed49d"

    readonly property color green_container: "#1f5027"

    readonly property color green_source: "#81c784"

    readonly property color green_value: "#81c784"

    readonly property color inverse_on_surface: "#2f3036"

    readonly property color inverse_primary: "#495d92"

    readonly property color inverse_surface: "#e3e2e9"

    readonly property color on_background: "#e3e2e9"

    readonly property color on_error: "#690005"

    readonly property color on_error_container: "#ffdad6"

    readonly property color on_green: "#043912"

    readonly property color on_green_container: "#b9f0b7"

    readonly property color on_primary: "#192e60"

    readonly property color on_primary_container: "#dae1ff"

    readonly property color on_primary_fixed: "#001849"

    readonly property color on_primary_fixed_variant: "#314578"

    readonly property color on_secondary: "#2a3042"

    readonly property color on_secondary_container: "#dde2f9"

    readonly property color on_secondary_fixed: "#151b2c"

    readonly property color on_secondary_fixed_variant: "#414659"

    readonly property color on_surface: "#e3e2e9"

    readonly property color on_surface_variant: "#c5c6d0"

    readonly property color on_tertiary: "#422741"

    readonly property color on_tertiary_container: "#ffd6f9"

    readonly property color on_tertiary_fixed: "#2b122b"

    readonly property color on_tertiary_fixed_variant: "#5a3d58"

    readonly property color on_yellow: "#3e2e00"

    readonly property color on_yellow_container: "#ffdf93"

    readonly property color outline: "#8f909a"

    readonly property color outline_variant: "#45464f"

    readonly property color primary: "#b3c5ff"

    readonly property color primary_container: "#314578"

    readonly property color primary_fixed: "#dae1ff"

    readonly property color primary_fixed_dim: "#b3c5ff"

    readonly property color scrim: "#000000"

    readonly property color secondary: "#c1c6dd"

    readonly property color secondary_container: "#414659"

    readonly property color secondary_fixed: "#dde2f9"

    readonly property color secondary_fixed_dim: "#c1c6dd"

    readonly property color shadow: "#000000"

    readonly property color source_color: "#0c1f4a"

    readonly property color surface: "#121318"

    readonly property color surface_bright: "#38393f"

    readonly property color surface_container: "#1e1f25"

    readonly property color surface_container_high: "#292a2f"

    readonly property color surface_container_highest: "#33343a"

    readonly property color surface_container_low: "#1a1b21"

    readonly property color surface_container_lowest: "#0d0e13"

    readonly property color surface_dim: "#121318"

    readonly property color surface_tint: "#b3c5ff"

    readonly property color surface_variant: "#45464f"

    readonly property color tertiary: "#e1bbdc"

    readonly property color tertiary_container: "#5a3d58"

    readonly property color tertiary_fixed: "#ffd6f9"

    readonly property color tertiary_fixed_dim: "#e1bbdc"

    readonly property color yellow: "#e5c36c"

    readonly property color yellow_container: "#594400"

    readonly property color yellow_source: "#f9e2af"

    readonly property color yellow_value: "#f9e2af"

}

